anu0012/awesome-computer-science-opportunities

README.md

edX is a non-profit organization founded by MIT and Harvard and works together with multiple other Universities and Organizations to provide awesome free courses.

Add edX to the MOOC section

---

README.md

A new addition to the IT fields for computer science undergraduates . A.I. was missing which is a very evolving tech and so I thought it would be better to add it :)

# Artificial Intelligence Resources

---

README.md

A subscription-based service that emails you whenever a new issue is opened in the repo that you've subscribed to.

Re: #1 Added CodeTriage

---

README.md

- CodeWars - similar to leetcode
- tapasweni-pathak's Summer Of Code list
- BaseCS as an explainer resource

Added CodeWars, SOC list, CS resource

---

README.md

It's an okay resource, but generally not encouraged by the community because he doesn't adhere to good coding conventions (like naming variables and functions properly). It can inadvertently cause newbies to develop bad habits that could end up as bad code smells later on in their journey.

Remove The New Boston

---

README.md

Add W3Schools and Eloquent JS to web dev section, add descriptions for the rest of the links in web dev section

update web dev section

---

README.md

Added:
-Khan Academy
-Exercism
-Visual Studio Dev Essentials
-Open Source Friday

Added descriptions and new resources.

---

README.md

Add Hacktoberfest to Opensource section.

Add Hacktoberfest

---

README.md

Added SoloLearn, one of the most famous free platforms to learn coding from.
#16 #1

#16  #1 Added an MOOC 

---

README.md

hack.summit() and Yelp Dataset Challenge to Hackathons section

Add items to hackathons section

---

README.md

Code craft and coder-coder added

Added web development learning platforms

---

README.md

Added a few cool opportunities that may be of use!
1. KPMG Data Science Virtual Internship - learn how data science is used in industry
2. Y Combinator 'Learn how to work at a startup' - learn how engineering is done in Y Combinator-backed startups

Added Y Combinator & KPMG engineering related opportunities

---

README.md

Fix the links for IEEEXtreme and Yelp Dataset Challenge

Fix two links (Issue #42)

---

README.md

Added "Scrimba" as a free Web Development resource. It has a unique feature which allows live interaction with code being written by instructor throughout the lecture.

Add Web Development resource

---

README.md

Add a few russian contest platforms

Add a few contest platforms

---

README.md

Infosec resources added

---

README.md

Added FrontendMasters as a resource in Web Development section

FrontendMasters

---

README.md

Corrected some misspelt words and added Adobe's scholarship to the Fellowship/Scholarship section.

fixed some typos and added Adobe's Women Scholarship

---

README.md

I mainly added opportunities to the competitive coding section, but also included some in the AI and hackathon sections.

Added more opportunities

---

README.md

Added [CodeCrafters](https://app.codecrafters.io/tracks). Lets you recreate complex software like Redis, Git, Docker, and SQLite from scratch, providing a deep understanding of how these tools work.

Added CodeCrafters
